CREATE TABLE categoria (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE clientes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(255) NULL,
	documento varchar(255) NULL,
	email varchar(255) NULL,
	nombre varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT clientes_pkey PRIMARY KEY (id)
);

CREATE TABLE nota_envio (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha date NULL,
	nro int8 NULL,
	observacion varchar(255) NULL,
	procesado int4 NULL,
	proveedor varchar(255) NULL,
	verificado int4 NULL,
	CONSTRAINT nota_envio_pkey PRIMARY KEY (id)
);

CREATE TABLE roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE producto (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	estado bool NULL,
	nombre varchar(100) NOT NULL,
	precio float8 NULL,
	stock int4 NULL,
	categoria_id int4 NULL,
	CONSTRAINT producto_pkey PRIMARY KEY (id),
	CONSTRAINT fkodqr7965ok9rwquj1utiamt0m FOREIGN KEY (categoria_id) REFERENCES categoria(id)
);

CREATE TABLE usuarios (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activo bool NULL,
	"password" varchar(255) NULL,
	username varchar(255) NULL,
	rol_id int8 NULL,
	CONSTRAINT usuarios_pkey PRIMARY KEY (id),
	CONSTRAINT fkqf5elo4jcq7qrt83oi0qmenjo FOREIGN KEY (rol_id) REFERENCES roles(id)
);

CREATE TABLE ventas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha date NULL,
	procesado int4 NULL,
	total_gravada float8 NULL,
	total_iva float8 NULL,
	total_venta float8 NULL,
	cliente_id int8 NULL,
	CONSTRAINT ventas_pkey PRIMARY KEY (id),
	CONSTRAINT fk4dgjhccl2uuo8swmxlxb4ipb5 FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE TABLE detalle_nota_envio (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cantidad int4 NULL,
	precio float8 NULL,
	nota_envio_id int8 NULL,
	producto_id int8 NULL,
	CONSTRAINT detalle_nota_envio_pkey PRIMARY KEY (id),
	CONSTRAINT fkj7km78q5mmv1ba3y8n5rm7lch FOREIGN KEY (producto_id) REFERENCES producto(id),
	CONSTRAINT fkqmno1r60x736mebh3c7jlw2h2 FOREIGN KEY (nota_envio_id) REFERENCES nota_envio(id)
);

CREATE TABLE detalle_ventas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cantidad int4 NULL,
	gravada float8 NULL,
	iva float8 NULL,
	precio_unitario float8 NULL,
	subtotal float8 NULL,
	producto_id int8 NULL,
	venta_id int8 NULL,
	CONSTRAINT detalle_ventas_pkey PRIMARY KEY (id),
	CONSTRAINT fk2dn1sdhrbmva44wbs9fy6l7mn FOREIGN KEY (venta_id) REFERENCES ventas(id),
	CONSTRAINT fkm7fycj8kls21medf66deqspgd FOREIGN KEY (producto_id) REFERENCES producto(id)
);