spring.application.name=sz53

# Configuración conexión DB Local (DBeaver / Mac local)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/prueba
spring.datasource.username=nahuel
spring.datasource.password=peosb123

# Configuración JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect