# Configuración conexión DB dentro de la red de Docker
spring.datasource.url=jdbc:postgresql://db:5432/prueba
spring.datasource.username=nahuel
spring.datasource.password=peosb123

# Mantenemos las tablas intactas respetando los scripts del init-scripts
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true